# Generated by Django 6.0.5 on 2026-05-06 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва валюти')),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс продажу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Курс валюти',
                'verbose_name_plural': 'Курси валют',
            },
        ),
        migrations.CreateModel(
            name='SavedDailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва валюти')),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс продажу')),
                ('saved_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата збереження')),
            ],
            options={
                'verbose_name': 'Збережений курс дня',
                'verbose_name_plural': 'Збережені курси дня',
            },
        ),
    ]
